/**
* Generated by go-doudou v1.3.7.
* Don't edit!
 */
package httpsrv

import (
	"github.com/unionj-cloud/go-doudou/v2/framework"
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type StatsvcHandler interface {
	Add(w http.ResponseWriter, r *http.Request)
	GetEcho(w http.ResponseWriter, r *http.Request)
}

func Routes(handler StatsvcHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "Add",
			Method:      "POST",
			Pattern:     "/add",
			HandlerFunc: handler.Add,
		},
		{
			Name:        "GetEcho",
			Method:      "GET",
			Pattern:     "/echo",
			HandlerFunc: handler.GetEcho,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}
